[build]
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/@pagedao/core/**"]

[functions.books]
  included_files = ["node_modules/@pagedao/core/**"]

[functions.collections]
  included_files = ["node_modules/@pagedao/core/**"]

[functions.authors]
  included_files = ["node_modules/@pagedao/core/**"]

[functions.metrics]
  included_files = ["node_modules/@pagedao/core/**"]

[functions.frame-webhooks]
  included_files = ["node_modules/@pagedao/core/**"]

[dev]
  port = 8888
  publish = "public"
